CREATE TABLE ENDERECO(
ID_ENDERECO INTEGER NOT NULL PRIMARY KEY,
RUA VARCHAR(200),
NUMERO VARCHAR(10),
BAIRRO VARCHAR(200),
COMPLEMENTO VARCHAR(200),
CEP VARCHAR(9),
CIDADE VARCHAR(200),
ESTADO VARCHAR(200));

CREATE SEQUENCE SEQ_ID_ENDERECO AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE DISCIPLINA(
ID_DISCIPLINA INTEGER NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(200));

CREATE SEQUENCE SEQ_ID_DISCIPLINA AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE PACIENTE(
ID_PACIENTE INTEGER NOT NULL PRIMARY KEY,
ID_ENDERECO INTEGER,
NOME VARCHAR(200),
DATA_NASCIMENTO DATE,
SEXO VARCHAR(1),
RG VARCHAR(12),
CPF VARCHAR(14),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(200),
PESO NUMERIC(15,3),
ALTURA NUMERIC(15,3),
COR VARCHAR(10),
ESCOLARIDADE VARCHAR(50),
PROFISSAO VARCHAR(200),
ESTADO_CIVIL VARCHAR(50),
NATURALIDADE VARCHAR(50),
ESTADO VARCHAR(50)
);

CREATE SEQUENCE SEQ_ID_PACIENTE AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE PROFISSIONAL(
ID_PROFISSIONAL INTEGER NOT NULL PRIMARY KEY,
ID_ENDERECO INTEGER,
NOME VARCHAR(200),
DATA_NASCIMENTO DATE,
SEXO VARCHAR(1),
RG VARCHAR(12),
CPF VARCHAR(14),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(200),
CRO VARCHAR (10));

CREATE SEQUENCE SEQ_ID_PROFISSIONAL AS INTEGER START WITH 1 INCREMENT BY 1;

CREATE TABLE SUPERVISOR(
ID_SUPERVISOR INTEGER NOT NULL PRIMARY KEY,
ID_DISCIPLINA INTEGER,
ID_ENDERECO INTEGER,
NOME VARCHAR(200),
DATA_NASCIMENTO DATE,
SEXO VARCHAR(1),
RG VARCHAR(12),
CPF VARCHAR(14),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(200),
CRO VARCHAR (10));

CREATE SEQUENCE SEQ_ID_SUPERVISOR AS INTEGER START WITH 1 INCREMENT BY 1;

